### ISSUE TITLE
Arduino hardware "photo resitor"

### ISSUE THREAD

**Issue by tobru** [MortenMiddelthon/powerduino#1]
Hi,

Thanks a lot for sharing this very interesting project. Could you please add some more information about the "photo resitor", what exactly are you using here? Maybe a little diagram which shows how to connect things to the arduino would also help (I'm really a beginner here).
Also interesting would be to have a short description how the data collection with the photo resistor works: How does it count the power usage? Is every "flash" from the power counter 1Wh?

**Comment by MortenMiddelthon** [comment]
Hi there,

Yes, the info is a little lacking. I'll do an update to the project documentation this weekend

With regards, Morten

Sent from my Samsung device

-------- Original message --------

**Comment by MortenMiddelthon** [comment]
Hi,

I just updated the README-file with a parts list

**Comment by MortenMiddelthon** [comment]
Also added a picture of how I have connected everything up:

https://github.com/MortenMiddelthon/powerduino/blob/master/images/powerduino01.png
